### PR TITLE
Fix issue with Bicep compilation failures being swallowed

### LINKED ISSUE #149: Action passing with non-zero output
Hello.

The Github action is passing, even if the execution of the az deployment command exits with a non-zero output.

As an exemple, the following `main.bicep` file is incorrect, because the name parameters is required:
```
module storageAccount 'br/public:avm/res/storage/storage-account:0.18.0' = {
  name: 'storageAccountDeployment'
  params: {
    // Required parameters
    //name: 'ssablob001'
  }
}
```
If I run a `validate` locally, it gives an error and exits with code `1`:

Image

When running a workflow with the bicep-deploy action like so:
```
   - name: Validate
      uses: azure/bicep-deploy@v2
      with:
        type: deployment
        operation: validate
        name: Development
        scope: resourceGroup
        resource-group-name: azure
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        template-file: ./main.bicep
        parameters-file: ./params.json
```
It results in the error message in the standard output, but the action completes with passing status.

Image

In fact the same happens to what-if and create: the error message in the output but a passing status in the actions and in the workflow as a whole.

This is causing confusion in my current project as users see the workflow completed with success only to discover later that it didn't work. In a more complex workflow, with several steps and dependencies, it is harder to track where the error is if no clear indication is given by the action.

The expected behaviour is to fail the action if the deployment fails. Either it fails by default with a flag to ignore it, or it passes by default (the current situation) with a flag to make it fail if the deployment fails.

The complete code to reproduce this scenario is here: https://github.com/nu12/azure-bicep-deploy

Thank you

### PR DESCRIPTION
**Pull request by anthony-c-martin**
Closes #149

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -97,8 +97,8 @@ export type DeploymentStackConfig = CommonConfig & {
   };
   denySettings: {
     mode: "denyDelete" | "denyWriteAndDelete" | "none";
-    excludedActions: string[];
-    excludedPrincipals: string[];
```
Comment (anthony-c-martin) [inline src/config.ts:101]: This change was necessary because of an accidental behavioral change to Stacks which would reject an empty array. I've also submitted a PR to fix the Stacks behavior, but it'll take some time before it is deployed.

**Review by ljtill — APPROVED** [review]
