### PR TITLE
Workaround for SDK formatting issue

### LINKED ISSUE #71: Incorrect Formatting in "What-If" Output
**Description**
The action is displaying the "what-if" changes incorrectly. Instead of showing structured changes, the output is displayed letter by letter, making it difficult to read and understand.

**Steps to Reproduce**
1. Run the "bicep deploy" GitHub action with "what-if" enabled to preview changes.
2. Observe the output, which displays each change as individual letters rather than a full line or structured format.

**Expected Behavior**
The "what-if" changes should be displayed in a clear, structured format (e.g., line by line or by property), allowing for easy review of changes.

**Actual Behavior**
See workflow run: https://github.com/Latzox/quickstart-azure-app-service-api/actions/runs/11662846647/job/32470028349
Or screenhot below:
Image

**Additional infos**
```
Action config: {
  "type": "deployment",
  "name": "11662846647",
  "location": "switzerlandnorth",
  "templateFile": "/home/runner/work/quickstart-azure-app-service-api/quickstart-azure-app-service-api/deploy/main.bicep",
  "parameters": {
    "subIdSharedServices": "***",
    "subIdSampleApi": "***"
  },
  "tags": {},
  "maskedOutputs": [],
  "operation": "whatIf",
  "scope": {
    "type": "subscription",
    "subscriptionId": "***"
  },
  "whatIf": {
    "excludeChangeTypes": []
  }
}
Installed Bicep version 0.30.[23](https://github.com/Latzox/quickstart-azure-app-service-api/actions/runs/11662846647/job/32470028349#step:5:24) to /tmp/bicep
```

Pipeline definition:
```
- name: Preview Deployment
        uses: azure/bicep-deploy@v1
        with:
          type: deployment
          operation: whatIf
          name: ${{ github.run_id }}
          location: ${{ env.AZURE_REGION }}
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: deploy/main.bicep
          parameters: |
            {
              "subIdSharedServices": "${{ secrets.AZURE_SUBSCRIPTION_ID_SS }}",
              "subIdSampleApi": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }
```

### PR DESCRIPTION
**Pull request by anthony-c-martin**
Closes #71

This appears to be an issue in how the node SDK is returning data from the WhatIf operation. I couldn't find any good options for tweaking this behavior, and so I've had to put in a workaround for it.

### CODE REVIEW

File: src/helpers/whatif.ts [hunk 1]
```diff
@@ -484,6 +484,33 @@ function formatPropertyDelete(
...
+    // be specific here with the check, to minimize the chance of
+    // accidentally trying to convert a value that genuinely should be an object.
+    if (typeof nextChar !== "string" || nextChar.length !== 1) {
+      return value;
+    }
+
+    fixedString += nextChar;
+  }
+
+  return fixedString;
```
Comment (anthony-c-martin) [inline src/helpers/whatif.ts:511]: This is a really ugly hack. However, by the time we get to this stage, I couldn't really find any good options for detecting the problem, and so I had to take this heuristic-based approach.

**Review by ljtill — APPROVED** [review]
